# Generated by Django 4.0.5 on 2022-06-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0004_remove_post_name_post_materialname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tutor',
        ),
    ]
