# Generated by Django 4.0.5 on 2022-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0005_remove_post_practice_remove_post_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
