# Generated by Django 4.0.5 on 2022-06-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0006_alter_post_fname_alter_post_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
