# Generated by Django 4.0.5 on 2022-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0009_alter_post_image_alter_post_pracfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/saleImgs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pracFile',
            field=models.FileField(blank=True, upload_to='staticpracticeFiles'),
        ),
    ]
