# Generated by Django 4.0.5 on 2022-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0011_alter_post_pracfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
