# Generated by Django 4.0.5 on 2022-06-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0013_remove_post_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='materialName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
