# Generated by Django 4.0.5 on 2022-06-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0014_alter_post_materialname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pracFile',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
