# Generated by Django 4.0.5 on 2022-06-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pracFile',
            field=models.FileField(blank=True, upload_to='media/files'),
        ),
    ]
